### ISSUE TITLE
Swift Package ?

### ISSUE THREAD

**Issue by sdamale** [amadeus4dev/amadeus-swift#1]
Readme says swift package is available, but it doesn't look like it is.

**Comment by sdamale** [comment]
OK I guess I figured it out. There is no version or version range for your package. So the idea is to select "branch" instead of "version" when you add Swift Package from XCode Swift Package Manager User Interface.

**Comment by sdamale** [comment]
In your readme.

>> var amadeus = new Amadeus(); 
should be 
<<  var amadeus = Amadeus()

Also, though obvious, please mention to write
import Amadeus

you may start feeling I am nagging but I hope the idea of hackathon is to popularize your platform and improving your api, tools, code and docs.

**Comment by alnacle** [comment]
Hey! Thanks for a lot for your comments! We have been working on the SDK for the last weeks but unfortunately is not fully ready. That's why we haven't release 1.0.0 version yet and the repo is not pinned like the rest of SDKs: You might have seen some tests are failing, documentation should be double checked, etc. However, endpoints work and you can use the branch instead of version when importing if you like to. We would be happy to receive feedback and pull requests :-)
